services:
  frontend:
    build: /frontend
    container_name: "frontend"
    ports:
      - "5173:5173"
    networks:
      - mern
      
  backend:
    build: /backend
    container_name: "backend"
    ports: 
      - "5050:5050"
    networks:
      - mern
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern
    volumes:
      - mongo-data:/data/db

networks:
  mern:
    driver: bridge

volumes:
  mongo-data:
    driver: local
